import{a as L,S as v,i as a}from"./assets/vendor-BzajH6aU.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();function h(r){return r.map(({webformatURL:t,largeImageURL:s,tags:n,likes:e,views:o,comments:i,downloads:y})=>`
    <li class="item">
        <a href="${s}">
          <img src="${t}" alt="${n}"/>
          <div>
            <p>Likes ${e}</p>
            <p>Views ${o}</p>
            <p>Comments ${i}</p>
            <p>Downloads ${y}</p>
          </div>
        </a>
      </li>`).join("")}async function p(r,t){return(await L(`https://pixabay.com/api/?key=47091591-3a0c1be132fb67c8f1fe23cd9&q=${r}&page=${t}&per_page=15&image_type=photo&orientation=horizontal&safesearch=true`)).data}const f=document.querySelector(".search-form"),m=document.querySelector(".gallery"),u=document.querySelector(".loader"),l=document.querySelector(".load-more-btn");let c=1,d="";const g=new v(".gallery a");f.addEventListener("submit",w);l.addEventListener("click",b);function w(r){if(r.preventDefault(),d=f.elements.query.value.trim(),d===""){a.warning({message:"enter something for search"});return}c=1,m.innerHTML="",u.classList.remove("hidden"),p(d,c).then(t=>{if(console.log(t),t.hits.length===0){a.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=h(t.hits);m.insertAdjacentHTML("beforeend",s),g.refresh(),t.totalHits>15?l.classList.remove("hidden"):l.classList.add("hidden")}).catch(t=>{console.log(t),a.error({message:"Oops, something went wrong!"})}).finally(()=>{u.classList.add("hidden"),f.reset()})}async function b(){c+=1,u.classList.remove("hidden");try{const r=await p(d,c),t=h(r.hits);m.insertAdjacentHTML("beforeend",t),g.refresh(),S(),Math.ceil(r.totalHits/15)>c?l.classList.remove("hidden"):(l.classList.add("hidden"),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.log(r),a.error({message:"Oops, something went wrong!"})}finally{u.classList.add("hidden")}}function S(){const r=document.querySelector(".item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
